### ISSUE TITLE
added feature flag 'vendored' for including openssl for native-tls

### ISSUE THREAD

**Issue by cattyhouse** [naresh97/trojan-rs#14]
with this feature enabled in Cargo.toml, it is able to cross compile musl static target with `cargo-zigbuild`

**Comment by naresh97** [comment]
Thanks for the tip. I haven't considered compiling with musl instead of glibc. It'll be interesting to see what can of binary sizes I can get with it.

**Comment by naresh97** [comment]
> it's about 4MB with feature socks5 only for aarch64-unknown-linux-musl

I'm surprised. Did you compile with `--release` ? The current build with glibc is ~800KB

**Comment by naresh97** [comment]
Ah, now I understand. Hmm, you are using Cross to cross-compile? Maybe if you installed openssl in the build environment, then you don't need to use `vendored` ?

**Comment by naresh97** [comment]
Yes, that's a good option to have. I'll implement this as a feature flag too.
